### ISSUE TITLE
halp!

### ISSUE THREAD

**Issue by ghost** [astronouth7303/rconbot#1]
So I've been getting tracebacks every which way.
I even tried making you a setup.py
I'm pretty sure I could fix myself, but not without going through and hacking up your code.
Thought I'd ask your advice first.

```
root@localhost:~/rconbot-master# ls -l
total 68
-rw-r--r-- 1 root root  8595 Jul 26  2008 bot.py
-rw-r--r-- 1 root root   221 Jul 26  2008 __init__.py
-rw-r--r-- 1 root root 14791 Apr 22 20:17 nexfs.py
-rw-r--r-- 1 root root 11870 Jul 26  2008 nexuiz.py
-rw-r--r-- 1 root root  7945 Jul 26  2008 rcon.py
-rw-r--r-- 1 root root  1144 Jul 26  2008 sample.py
-rw-r--r-- 1 root root   291 Apr 22 20:34 setup.py
-rw-r--r-- 1 root root  6188 Jul 26  2008 utils.py
root@localhost:~/rconbot-master# python bot.py
Traceback (most recent call last):
  File "bot.py", line 10, in <module>
    from .nexuiz import NexRcon, Commands
ValueError: Attempted relative import in non-package
root@localhost:~/rconbot-master# python nexfs.py
_loaddirs: ['/root/.nexuiz/data/data', './data']
Traceback (most recent call last):
  File "nexfs.py", line 511, in <module>
    nfs.reload()
  File "nexfs.py", line 218, in reload
    self._loaddirs()
  File "nexfs.py", line 210, in _loaddirs
    for fn in sorted(os.listdir(d)):
OSError: [Errno 2] No such file or directory: './data'
root@localhost:~/rconbot-master# python nexuiz.py
Traceback (most recent call last):
  File "nexuiz.py", line 14, in <module>
    from .rcon import Rcon
ValueError: Attempted relative import in non-package
root@localhost:~/rconbot-master# python rcon.py
Traceback (most recent call last):
  File "rcon.py", line 17, in <module>
    from rconbot.utils import quote
ImportError: No module named rconbot.utils
root@localhost:~/rconbot-master# 
```

**Comment by ghost** [comment]
RE: OSError: [Errno 2] No such file or directory: './data'

I've tried moving rconbot-master folder all over the place to get it to acknowledge that YES, I do have a /data/data folder. But it doesn't seem to care.

**Comment by AstraLuma** [comment]
Yeah, I need to refactor to do proper setup and then dig out the scripts that actually used this for examples. I suggest creating a project and checking out `rconbot` inside it or as a git submodule. Then your scripts refer to `rconbot.bot`, etc. See `sample.py` for how bot scripts are supposed to work.

`nexfs.py` is the probably the file giving you trouble. It was written for a Linux file layout. What's probably happening is that you're missing `~/.nexuiz/data/data`, which is the default directory it searches for .pk3's and other nexuiz files. I never bothered testing on Windows because I never use it.

I'll pull my old nexuiz server configuration in the next few days and refactor this project to actually be usable/installable.

**Comment by AstraLuma** [comment]
(As an aside: It's a good idea to not run nexuiz or any bots as root.)

**Comment by ghost** [comment]
I'm using debian linux
and yes i have ~/.nexuiz/data/data

**Comment by AstraLuma** [comment]
As of bcbaea2214, `rconbot` should be installable. I suggest using `sudo python2 setup.py develop` so that you don't have reinstall every time you make a change or fix something.

**Comment by ghost** [comment]
ty!

**Comment by AstraLuma** [comment]
Committed the script I actually used in my setup. It automatically changed game mode at random.

If you have any more examples, feel free to make a pull request.
